version: "3"
volumes:
  pgdata:
services:
  pagila:
    image: postgres:14.15
    container_name: pagila
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
    volumes:
      - ./pagila/1-pagila-schema.sql:/docker-entrypoint-initdb.d/1-pagila-schema.sql
      - ./pagila/1-pagila-schema-jsonb.sql:/docker-entrypoint-initdb.d/1-pagila-schema-jsonb.sql
      - ./pagila/2-pagila-data.sql:/docker-entrypoint-initdb.d/2-pagila-data.sql
      - ./pagila/3-pagila-data-yum-jsonb.backup:/docker-entrypoint-initdb.d/3-pagila-data-yum-jsonb.backup
      - ./pagila/3-pagila-data-apt-jsonb.backup:/docker-entrypoint-initdb.d/3-pagila-data-apt-jsonb.backup
      - ./pagila/3-restore-pagila-data-jsonb.sh:/docker-entrypoint-initdb.d/3-restore-pagila-data-jsonb.sh
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - "./pgadmin/pgadmin_servers.json:/pgadmin4/servers.json"
      - "./pgadmin/pgadmin_pass:/pgadmin4/pass"
    ports:
      - "5050:80"
   
